### ISSUE TITLE
redefine origami keybindings

### ISSUE THREAD

**Issue by kofifus** [SublimeText/Origami#102]
new to sublime so may be missing something obvious...

To my Default (Windows).sublime-keymap I added:

```
{ "keys": ["super+up"], "command": "travel_to_pane", "args": {"direction": "up"} },
{ "keys": ["super+right"], "command": "travel_to_pane", "args": {"direction": "right"} },
{ "keys": ["super+down"], "command": "travel_to_pane", "args": {"direction": "down"} },
{ "keys": ["super+left"], "command": "travel_to_pane", "args": {"direction": "left"} },
```

However this doesn't work - that is for example win+up does not go to pane above.

What's wrong ?

**Comment by MattDMo** [comment]
Try this: open the console with <kbd>Ctrl</kbd><kbd>`</kbd> and enter
```python
sublime.log_commands(True)
```
Then, with the console still open, click in a pane and try each of your key combos and see what's printed in the console. A successful execution will read something like:
```
command: travel_to_pane {"direction": "up"}
```
It's quite possible that Windows already uses these key combinations for something else (I'm not on Win, so I can't say right now if that's true), so the next thing to try would be to add a modifier key like <kbd>Ctrl</kbd>:
```json
{ "keys": ["super+ctrl+up"], "command": "travel_to_pane", "args": {"direction": "up"} },
```
and see if that works.

**Comment by kofifus** [comment]
yes you're right it's a windows shortcut.
is there no way to override these ?

**Comment by adzenith** [comment]
I just googled a little and found e.g. this: https://www.sevenforums.com/tutorials/5937-windows-key-shortcuts-enable-disable.html
Closing as Origami can't fix this issue.
