### ISSUE TITLE
Is there a way to make autocomplete to also work cloned windows?

### ISSUE THREAD

**Issue by nikitavoloboev** [SublimeText/Origami#103]
This would really be useful and I don't really know why it does not work, perhaps it is a bug.

**Comment by adzenith** [comment]
Can you describe in more detail what behavior you're trying to see?

**Comment by nikitavoloboev** [comment]
Hey adzenith,

Sorry for a late reply. Here is a screencast I made to clarify better on what I mean : http://quick.as/l91Xf2g4O.

**Comment by adzenith** [comment]
It looks like this is a bug in Sublime. Can you try:

- make a new window
- go View>Layout>Columns: 2
- open a file
- go File>New View Into File
- drag the new view on the tab bar into the other column
- see if they both have autocomplete

**Comment by FichteFoll** [comment]
Definitely an issue with sublime text. Probably https://github.com/SublimeTextIssues/Core/issues/731.

Does the problem go away after a ST restart?

**Comment by nikitavoloboev** [comment]
Yeah, I tried the steps adzenith proposed and got the same issue.

So if it is a sublime text bug, do you know if there is a way to fix it. I have googled it and looked at the link posted by FichteFoll and it seems that it still has not been fixed. 

Should I just wait for it to be fixed by the Sublime Text team or there is something else I could do?

Thank you for your help.

**Comment by FichteFoll** [comment]
If a ST restart does not fix it (you didn't mention that), then there is nothing you can do.

**Comment by adzenith** [comment]
Yeah, you're going to have to wait and see if it gets fixed in Sublime Text. Sorry about that.
