### ISSUE TITLE
Inconsistent background color until window is focused

### ISSUE THREAD

**Issue by saadq** [SublimeText/Origami#104]
When I create any new panes with Origami, they seem to have a very different background color:

<img width="1392" alt="screen shot 2016-05-10 at 2 35 46 pm" src="https://cloud.githubusercontent.com/assets/5678694/15158144/81e69038-16bc-11e6-823b-02e83b1f4ab3.png">

Once I click on one of the panes, the discoloration is fixed everywhere:

<img width="1392" alt="screen shot 2016-05-10 at 2 36 12 pm" src="https://cloud.githubusercontent.com/assets/5678694/15158161/8f377a5e-16bc-11e6-857a-725e17daf505.png">

Is there a way to prevent this discoloration? I don't think it's a theme issue because the same thing happens no matter what theme I use.

**Comment by FichteFoll** [comment]
This color is specified by your theme, iirc. I don't know which identifier it is exactly though. I suggest asking/noting this at your theme's repo.

**Comment by saadq** [comment]
Is that definitely the case? I've tried it out with a few themes and they all seem to have the same result:

Default:

<img width="1392" alt="screen shot 2016-05-10 at 4 11 37 pm" src="https://cloud.githubusercontent.com/assets/5678694/15160927/092a1940-16ca-11e6-9bb1-6babbb6dcf17.png">

Spacegray:

<img width="1392" alt="screen shot 2016-05-10 at 4 11 57 pm" src="https://cloud.githubusercontent.com/assets/5678694/15160939/10f5e438-16ca-11e6-8e1d-2fc283efa1fc.png">

Material:

<img width="1392" alt="screen shot 2016-05-10 at 4 12 18 pm" src="https://cloud.githubusercontent.com/assets/5678694/15160945/18e65844-16ca-11e6-9557-f4094558a88f.png">

I'll definitely look into the theme settings though.

**Comment by delk0** [comment]
This exact thing happens to me as well. I'm using the material theme.

**Comment by saadq** [comment]
Yup, and it looks like it isn't theme or color-scheme dependent, the issue seems to happen with everything I choose.

**Comment by adzenith** [comment]
The reason this happens is because there's no file there yet. When you click Sublime Text makes a fake default file that disappears if you open something else. I'm not sure if it's possible to make one of these fake files programmatically. I can look into it.
