### ISSUE TITLE
Auto zoom pane not working?

### ISSUE THREAD

**Issue by Gabriel-p** [SublimeText/Origami#108]
I have Sublime 3 divided into three panes.

I added the `origami_auto_zoom_on_focus` setting to my user preferences (BTW, this option is not mentioned in the preferences, not even set to `False`. Why?) and set it to `True`.

Nothing happens. If I move from one pan to another either by clicking a tab in the pane or via the shortcut `Ctrl+X`  (where x is the number of the pane), it is not zoomed.

The `Ctrl+k`+`Ctrl+z` shortcut does zoom a pane (I'm using Linux)

**Comment by evvvritt** [comment]
Try putting it in `Preferences.sublime-settings` (Preferences > Settings – User)
#107

**Comment by ragamufin** [comment]
@evvvritt 's suggestion worked for me, thanks!

**Comment by adzenith** [comment]
Closing as duplicate of #107.
