### ISSUE TITLE
travel_to_pane creates a new pane when it shouldn't

### ISSUE THREAD

**Issue by steelsojka** [SublimeText/Origami#109]
I have a key binding for navigating between panes.

```json
    { "keys": ["ctrl+h"], "command": "travel_to_pane", "args": { "direction": "left" }},
    { "keys": ["ctrl+l"], "command": "travel_to_pane", "args": { "direction": "right" }},
    { "keys": ["ctrl+k"], "command": "travel_to_pane", "args": { "direction": "up" }},
    { "keys": ["ctrl+j"], "command": "travel_to_pane", "args": { "direction": "down" }},
```

If I have a single pane and travel to a pane in any direction a new one is created. According to the code for the command it shouldn't unless the second arg is true. Is this intended?

**Comment by steelsojka** [comment]
I found the user setting for it :/ My bad.

**Comment by oscarmlage** [comment]
I've same issue, @steelsojka please could you paste the right setting to not open a new pane with "travel_to_pane" command?. Thanks in advance.

**Comment by oscarmlage** [comment]
Found the solution in the other issue:

`{
    "create_new_pane_if_necessary": false
}`
