### ISSUE TITLE
Clone command doesn't create pane if necessary

### ISSUE THREAD

**Issue by jgbishop** [SublimeText/Origami#112]
If I have only 1 pane open, and I issue the command "Clone File to Pane Below" (or any other direction for that matter), a clone of the file gets created, but the new pane does not. The clone command should support the `create_new_if_necessary` option, which it appears to lack. I note that both the `travel_to_pane` and `carry_file_to_pane` commands both support this option.

I saw a suggestion in issue #94 to chain two commands:

```
sublime.active_window().run_command("create_pane", {"direction": "right"})
sublime.active_window().run_command("copy_file_to_pane", {"direction": "right"})
```

Doing this, however, would result in a new pane every time (which I may not need). Adding the `create_new_if_necessary` option to the clone command would be a help.

**Comment by UniFreak** [comment]
#94 already issued this problem

**Comment by adzenith** [comment]
I don't suppose you want to submit a pull request? :) I'll probably be busy for the next couple weeks but might be able to add something in then.

**Comment by jgbishop** [comment]
I have added a commit to my fork that (I think) should fix this issue. Take a look at it and let me know if you spot anything that looks out of place.

**Comment by adzenith** [comment]
Looks great! Thanks so much. I think you're the first person who's ever submitted a PR after I suggested that they could. :+1:

**Comment by jgbishop** [comment]
:smile: Happy to help! I enjoy contributing to open source when I can.
