### ISSUE TITLE
Super Key In Ubuntu Not Working

### ISSUE THREAD

**Issue by balistikbill** [SublimeText/Origami#113]
It just unhides the "task bar" and doesn't zoon in with super+z.  ANy ides to fix this?

**Comment by adzenith** [comment]
Are you pressing `super+k, super+z` or just `super+z`? Have you tried rebinding it to a different key, or unbinding the default behaviour? I'm not at an Ubuntu machine right now.

**Comment by balistikbill** [comment]
Oh it's ctrl+k, ctrl+z.  The github repo said super.  Hmm, maybe that should be updated.

ctrl+k, ctrl+z works.  That's how it is listed in the default keybinding for Origami.

**Comment by adzenith** [comment]
Oh, that's right - there's a note at the bottom of the readme to that effect.

**Comment by adzenith** [comment]
I updated the readme to say "command" instead of "super" for clarity.
