### ISSUE TITLE
Cannot change key bindings

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [SublimeText/Origami#124]
No matter what I write in the user key bindings file, Origami ignores it and sticks with its defaults. My overrides are:

```javascript
[
  { "keys": ["super+alt+shift+up"], "command": "travel_to_pane", "args": {"direction": "up"} },
  { "keys": ["super+alt+shift+right"], "command": "travel_to_pane", "args": {"direction": "right"} },
  { "keys": ["super+alt+shift+down"], "command": "travel_to_pane", "args": {"direction": "down"} },
  { "keys": ["super+alt+shift+left"], "command": "travel_to_pane", "args": {"direction": "left"} },

  { "keys": ["super+alt+shift+ctrl+up"], "command": "carry_file_to_pane", "args": {"direction": "up"} },
  { "keys": ["super+alt+shift+ctrl+right"], "command": "carry_file_to_pane", "args": {"direction": "right"} },
  { "keys": ["super+alt+shift+ctrl+down"], "command": "carry_file_to_pane", "args": {"direction": "down"} },
  { "keys": ["super+alt+shift+ctrl+left"], "command": "carry_file_to_pane", "args": {"direction": "left"} },

  { "keys": ["super+alt+shift+backspace"], "command": "destroy_pane", "args": {"direction": "self"} },

  { "keys": ["super+alt+shift+plus"], "command": "zoom_pane", "args": {"fraction": 0.9} },
  { "keys": ["super+alt+shift+minus"], "command": "unzoom_pane", "args": {} }
]
```

Also, I thought I might try editing the defaults, but the file that's opened in Sublime is somehow "virtual". It doesn't exist on disk, and does not allow editing.

**Comment by DanielSmedegaardBuus** [comment]
Okay, if I manually create the file at the "virtual" path that is display in Sublime when opening the settings, I can override settings in the main Sublime user key bindings config. Strangely, after creating the Origami default bindings file, opening the user key bindings settings in the Origami preferences menu no longer opens its own keybindings file where I made my changes, but the main Sublime user key bindings file.

**Comment by DanielSmedegaardBuus** [comment]
Okay, and it crashes Sublime left and right when closing tabs or unzooming. Think I'm just gonna uninstall. Good idea, though! :+1:

**Comment by adzenith** [comment]
How strange... what's your setup?
The file is virtual because when you install using Package Manager it installs as a zip file, so when you open the file it's opening a file inside a zip file which can't be saved. You should still be able to override the bindings though... And it shouldn't crash when you close tabs. I don't see that behavior.
