### ISSUE TITLE
Auto focus on pane create

### ISSUE THREAD

**Issue by sotojuan** [SublimeText/Origami#125]
I'd like to request (or at least get some pointers on contributing to) a setting that will auto focus when creating a new pane (so, create pane to the right, then auto focus there). Something like`origami_create_auto_focus_on_create`.

**Comment by adzenith** [comment]
Yeah, you could add the setting and if it's true move to a pane after you create it. It should be reasonably straightforward. How can I help you?

**Comment by adzenith** [comment]
By default, `create_new_pane_if_necessary` is set to `true`, so you can just travel in a direction without a pane and it'll automatically make a pane and move you there.
