### ISSUE TITLE
"create_new_pane_if_necessary" not picked up from Preferences.sublime-settings

### ISSUE THREAD

**Issue by DrBones** [SublimeText/Origami#129]
Maybe I don't understand Sublime Texts setting hierarchy  correctly but some of the Origami settings like "origami_auto_zoom_on_focus" are read from the main user preference file except "create_new_pane_if_necessary".

I understand that I can set it from Origami.sublime-settings but then I cannot change it with Sublimes "set_setting" command and also I cannot make it project specific.

Is there a way to make Origami read that setting from my user preference file or am I doing something wrong here?

Thanks in Advance

**Comment by adzenith** [comment]
It looks like maybe this is not possible? https://forum.sublimetext.com/t/package-specific-key-binding-change-setting/14584

**Comment by DrBones** [comment]
Thanks for your reply!

That explains why I was unsuccessful in setting a package specific setting in my project settings :)

I still wonder though why Origami chooses to read some of its setting from Preferences.sublime-settings and some from the Origami.sublime-settings file. 

I worked around some of my trouble by specifying the additional parameter directly to `travel_to_plane` like:
```  
{ "keys": ["left"],    
  "command": "travel_to_pane",
   "args": {"direction": "left", "create_new_if_necessary": false},
 },
```
That was my main use case for `set_setting`, so this could be closed. Project specific settings would still be really nice and the inconsistency bothers me a little :)

**Comment by aMoniker** [comment]
Just ran into this issue as well. Origami expects `origami_auto_zoom_on_focus` to be in `Preferences.sublime-settings`, and won't work in `Origami.sublime-settings`. That's pretty unintuitive, so there should be a note in the README somewhere if it's not possible to keep all settings in one file.

**Comment by adzenith** [comment]
All preferences are now in the Origami.sublime-settings. Sorry for the confusion!
