### ISSUE TITLE
Command P not working in newly opened panel

### ISSUE THREAD

**Issue by BreadPaPa** [SublimeText/Origami#130]
First of all awesome package!

After I open a new panel using `command+k+arrow`, `command+p` does open the search box under new panel. But when I start typing the search box and new panel disappear, the typing starts in the original tab.

**Comment by adzenith** [comment]
Sounds like a bug! For now, try setting `origami_auto_close_empty_panes` to false?

**Comment by BreadPaPa** [comment]
@adzenith Sorry about the late reply. That worked! I used to set `origami_auto_close_empty_panes` to true, after changing to false the search function works. Hope you guys are aware of this bug. Thanks!

**Comment by adzenith** [comment]
Fixed in https://github.com/SublimeText/Origami/commit/1b5fd1a36ef884fdf79d079641e853fd3b3fc648.
