### ISSUE TITLE
Resize window to accommodate new panes

### ISSUE THREAD

**Issue by distefam** [SublimeText/Origami#131]
It's great that Origami makes it very easy to adjust the size and number of panes, however, it would be very helpful to have the ability to adjust the size of the SublimeText window to fit the panes (perhaps with rulers or max line size as guides?). 

Maybe this is already possible and I'm just not aware of it? Right now I use Origami to instantiate and destroy panes and a third-party tiling window manager tool (Spectacles) to resize the SublimeText window but it would be really great to be able to do this with one keyboard shortcut.

**Comment by adzenith** [comment]
Sadly plugins can't control the size or shape of the window itself (unless maybe the plugin punched out of Sublime Text and hooked into your windowing system?). Could you set up one shortcut in your window manager that resizes ST and then sends a keypress to ST to make more columns?
