### ISSUE TITLE
Pane focus doesn't affect command+# shortcuts anymore

### ISSUE THREAD

**Issue by cnees** [SublimeText/Origami#134]
Expected behavior:
command+2 takes me to the second tab in the focused pane

Observed behavior:
command+2 takes me to the second tab across all panes, regardless of which pane is focussed.

To reproduce:
Create two panes
Open two or more tabs in each
Focus on the righthand pane
command+1

This applies to command+1–9. It used to be possible to go to a tab in a pane, meaning you had easy access to the first eight tabs and last tab in any pane, and now you only have shortcuts for nine tabs regardless of how many panes you have open.

**Comment by adzenith** [comment]
Origami doesn't set up these keybindings. Perhaps something changed in Sublime Text?

**Comment by adzenith** [comment]
It looks like this is fixed in my local Sublime Text.
