### ISSUE TITLE
request: full screen pane

### ISSUE THREAD

**Issue by schmurfy** [SublimeText/Origami#140]
Is it possible to have a real zoom feature, one that maximize the panel to take the whole window space ? The current zoom is better than nothing but I have a small screen and I would love to have more space.

**Comment by nikoargo** [comment]
Have you tried setting the zoom factor higher?

**Comment by adzenith** [comment]
Have you tried setting the zoom factor higher?

**Comment by schmurfy** [comment]
thanks !
I was not aware of this parameter, setting it to 1 does what I wanted :)
