### ISSUE TITLE
keybinding precedence 

### ISSUE THREAD

**Issue by thejax** [SublimeText/Origami#146]
Hello,

I'm new to sublime so I'm not so sure it is related to Origami but more to a sublime misconfiguration.

I would like to use ctrl-j and ctrl-k to navigate in the list of files  (goto command) but I would also like to navigate through panes using the same keys. Hence, I'm having this in my user keymap file. 
  
```
{ "keys": ["ctrl+j"],"command": "move", "args": {"by": "lines", "forward": true}, "context":                                                             
 [                                                                                                 
 { "key": "overlay_visible", "operator": "equal", "operand": true },                         
 ]},                 
                                                                                  
 { "keys": ["ctrl+j"], "command": "travel_to_pane", "args": {"direction": "down"} },    
```  

But when I'm trying to use ctrl-j or ctrl-k to navigate in the list of files, origami systematically takes over and create a new pane on the bottom.

Any hint on how to solve this ? 

Thanks

**Comment by deathaxe** [comment]
I guess it is related with the order of your key bindings.

To avoid any issues with order etc, you could add the context to both bindings.

```JSON

    {
        "keys":["ctrl+j"], 
        "command":"move", 
        "args":{"by":"lines","forward":true},
        "context": [
            {"key":"overlay_visible","operand":true},
        ]
    },
    {
        "keys":["ctrl+j"],
        "command":"travel_to_pane",
        "args":{"direction":"down"},
        "context": [
            {"key":"overlay_visible","operand":false},
        ]
    },
```

**Comment by thejax** [comment]
@deathaxe  yep, this works. 

Funny though because I did tried before to change the order but without any success. Specifying the context to false did the trick. 

Many thanks.

**Comment by sourcevault** [comment]
Hi, @ngermeau, I had a quick question about the following text.

> I would like to use ctrl-j and ctrl-k to navigate in the list of files (goto command) but I would also like to navigate through panes using the same keys. Hence, I'm having this in my user keymap file.

why can't you use the up and down arrow key to navigate in the list of files ?
