### ISSUE TITLE
Auto close empty panes, destroed panes in different windows

### ISSUE THREAD

**Issue by pelemarse** [SublimeText/Origami#149]
If Origami settings is set `"origami_auto_close_empty_panes": true` and more than one windows opened. Example with two windows A and B --> When close one window (B), but pane destroyed in second (A).
![2019-05-24 23 05 40](https://user-images.githubusercontent.com/29234307/58354097-1762bc00-7e79-11e9-9d76-e0b33ea5d13c.gif)

**Comment by adzenith** [comment]
Ooh nice bug! I've reproduced on my end. I'll see if I can put in a fix.

**Comment by adzenith** [comment]
Should be fixed. Let me know if you see any other bugs!
