### ISSUE TITLE
ST4 - `auto_close_empty_panes` not working

### ISSUE THREAD

**Issue by danillos** [SublimeText/Origami#152]
I'm using ST4 and when I close the last file it didn't close the Panel.

**Comment by adzenith** [comment]
It works over here... any more info about your setup?

**Comment by danillos** [comment]
I recorded it. I'm using the latest ST4, no errors shows on the console when closing the last file.

![example](http://g.recordit.co/orU6NOZX5N.gif)

**Comment by adzenith** [comment]
Ah, I wasn't using ST4. Probably something changed in the new version? I can't find any release notes on the forum.

**Comment by danillos** [comment]
I'll attempt to help on it, I just need some time to stop and debug it.

**Comment by danillos** [comment]
If you want to see the ST4 unofficial changelog: https://gist.github.com/jfcherng/7bf4103ea486d1f67b7970e846b3a619#tab-multi-select

**Comment by danillos** [comment]
I opened a core issue that seems the reason of this issue: https://github.com/sublimehq/sublime_text/issues/3463

**Comment by danillos** [comment]
This was fixed in build 4087, see https://github.com/sublimehq/sublime_text/issues/3463
