### ISSUE TITLE
Vertical Height of Pane Restricted by Other Pane

### ISSUE THREAD

**Issue by Ithiloneth** [SublimeText/Origami#160]
Am I doing something wrong or is this an issue? This behavior seems counter intuitive to me.
The unwanted behavior is the limiting of the vertical size of the lower right side pane.
Rather than try to use words, and risk confusion, here's video:

https://user-images.githubusercontent.com/20944949/116560813-068f1080-a902-11eb-93d2-4fc4f1779e9a.mp4

**Comment by rchl** [comment]
Origami just creates panes using the ST API and doesn't control the resizing. So I'd suggest reporting this to the [ST bug tracker](https://github.com/sublimehq/sublime_text/issues) if it's not already reported.
