### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by codehangen** [SublimeText/Origami#172]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by rchl** [comment]
I'm one of the maintainers and, even though my time for this project is limited, I should be able to handle some pull requests and conversations.

If you come up with PRs, try to make those small and without including unrelated changes like refactorings or lint fixes (create separate PRs for those if needed).

Also feel free to discuss your intended changes beforehand to avoid extra work on both sides.
