### ISSUE TITLE
 how to remove the created pane?

### ISSUE THREAD

**Issue by macrotea** [SublimeText/Origami#25]
hello 
st2 works on win7
but i cant remove the the created pane on the right?
could u help me ? thx !!

**Comment by zencircle** [comment]
Closed and sublime text and opened again, double pane was gone

**Comment by brijbhan704** [comment]
You Click This Key
Shift+Alt+1

**Comment by sunil-17112** [comment]
> ok, i do it by your way,but no effect ! but i click "view" -> "layout" -> "single" , then all is ok

thanks
