### ISSUE TITLE
Destroy current pane

### ISSUE THREAD

**Issue by ckruse** [SublimeText/Origami#27]
A command to destroy the current pane would be nice; currently, destroy_pane only can destroy a pane left/right/upwards/downwards of the current frame; I'd like to have an Emacs-like feature for destroying a pane.

**Comment by AlexVKO** [comment]
Thank you!

my shortcut:

{ "keys": ["super+k", "super+w"], "command": "destroy_pane", "args": {"direction": "self"} }
