### ISSUE TITLE
Command to cycle open panes

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/Origami#29]
There are commands for focussing other panes but only with a direction. I wanted to have a command that just cycles through all open panes and this is it:
```python
import sublime_plugin


class CyclePanesCommand(sublime_plugin.WindowCommand):
    def run(self):
        w = self.window
        w.focus_group((w.active_group() + 1) % w.num_groups())
```

I thought this might be interesting for this plugin since it solves similar issues.
What could still be improved is location-aware cycling that goes from right to left and from top to bottom but since the cells from `window.get_layout()` are not ´guaranteed to be returned in order this is not reliable yet. Crawling through all the groups and their coordinates should be enough for that already but I didn't bother to implement this since I'm rarely using more than 3 panes anyway. Feel free to implement that though.

**Comment by adzenith** [comment]
Looks like this is implemented in https://github.com/wbond/package_control_channel/pull/4142 (https://github.com/daytonn/CycleGroup). Closing.
