### ISSUE TITLE
Cannot clone file to new pane

### ISSUE THREAD

**Issue by jcranendonk** [SublimeText/Origami#48]
With a single file open in a single pane, "Clone file to pane on the right" clones the file in the current pane. "Create pane with file on the right" creates a pane on the right and mvoes the file to the new pane.

I seem to remember that one of these commands allowed you to create a new pane and clone the current file to it.

**Comment by adzenith** [comment]
I just merged PR #87, which will make a new pane if you're moving in a direction where there is no pane. Does that solve your issue?

**Comment by jcranendonk** [comment]
Issue necromancy! Yes, I do believe that would resolve the issue. Thanks!
