### ISSUE TITLE
Make zoom toggle

### ISSUE THREAD

**Issue by WickyNilliams** [SublimeText/Origami#75]
Would it be possible to have the zoom functionality toggle? Once to zoom, same keystroke to unzoom. An explicit unzoom command seems redundant since it's a binary property.

The pseudocode would be something like:

```
if(zoomed(pane))
  unzoom(pane)
else 
  zoom(pane)
```

**Comment by adzenith** [comment]
Absolutely! In fact, that's such a good idea that we put it in there before you even asked for it :):)
Try binding to `toggle_zoom_pane`.
It occurs to me that this should maybe be in the command palette as well. I'll go add it.

**Comment by WickyNilliams** [comment]
Amazing, thanks for letting me know. I only raised this issue because I couldn't see it in the command palette,  so assumed functionality didn't exist. So probably wise to add the, yes. 

Thanks again

**Comment by WickyNilliams** [comment]
I've tried adding the following to my User key bindings:

```json
[
  { "keys": ["super+k", "super+z"], "command": "toggle_zoom_pane", "args": {"fraction": 0.9} }
]
```

But doesn't seem to do anything. Also tried commenting out commands from default binding (wasn't sure if this is necessary step). If i log commands in sublime console, it says it's executing `toggle_zoom_pane`, but nothing actually happens.

Anything obviously wrong with the above?

**Comment by adzenith** [comment]
How strange. I coped and pasted your keybinding and it works fine for me.
You shouldn't need to comment anything out in the default bindings.

Just to make sure—you have more than one pane open, right? :)

**Comment by WickyNilliams** [comment]
Yes, multiple panes open. For example, if I have user keybindings on left, some other file on right. Before adding new binding, zoom works fine. After adding toggle command binding, nothing happens. Though as I say, sublime logs that the command has executed:

```
command: toggle_zoom_pane {"fraction": 0.9}
```

Im using ST 2.0.2

**Comment by adzenith** [comment]
Oh, you're using ST 2! No wonder. Ok. It uses Python 2, which came free with the Suck™ feature. I'm checking in a fix.

**Comment by adzenith** [comment]
Should be fixed for everyone now.

**Comment by WickyNilliams** [comment]
Haha. Thanks for that, works perfectly now :)

Is there some process to notify Package Control about new versions? It reported no new versions, so I had to uninstall & install to pull in latest

**Comment by FichteFoll** [comment]
Package Control only checks for updates automatically on restart and then only every 60 minutes but you can trigger the check manually with **Package Control: Upgrade Package**.

**Comment by WickyNilliams** [comment]
@FichteFoll I did try that (plus a restart of ST), but still got the "No packages to upgrade" message.

**Comment by FichteFoll** [comment]
That, and releases in general take up to one hour to be noticed by the crawler and then get pushed to the channel file that is downloaded. I suspect that the manual install triggered resulted in PC downloading the updated info from the repo directly but this is just a theory.
