### ISSUE TITLE
Combining panes creates issues when editing files through ssh

### ISSUE THREAD

**Issue by zachhalle** [SublimeText/Origami#77]
For my school work I need to edit files that live on a remote server. I like to do so using sublime, which I am able to achieve using the rsub. Recently I installed origami to speed up my workflow. However I've run into some issues. If I open a remote file, create a new pane next to it, clone the file into that pane, and then try to recombine them using command-K, command-shift-<arrow> (or any other means) I am no longer able to save that file. I get a message saying "Unable to save /var/folders/cm/<long string of numbers, characters>/rsub-<more nums/chars>/<file-name>". This happens even if no edits were made to the file or its clone.

**Comment by adzenith** [comment]
This sounds like it's probably in rsub, not in Origami—we use the built-in file cloning functions, and Sublime Text automatically recombines the files when you close a pane with a clone in it. Have you filed a ticket over there? Have you tried manually cloning without using Origami?

**Comment by zachhalle** [comment]
Yeah, I believe this is an rsub issue. Sorry about that.
