### ISSUE TITLE
Cannot do automatic zoom (Sublime 3)

### ISSUE THREAD

**Issue by devjones** [SublimeText/Origami#78]
Here are the contents of my Origami user settings file:
````
{
	"origami_auto_zoom_on_focus": 0.95 
}
````
When I click on another pane, it does not automatically expand as I would have expected.  Am I doing this right or is there a bug?

**Comment by adzenith** [comment]
For historical reasons, you have to put it in your user preferences, not in your Origami preferences.

**Comment by devjones** [comment]
OK, it's now working when I put it in the 'Settings - User' file.  I don't know if I'm alone on this, but it may be helpful to make this distinction more clear in the README.  I would have expected either one to work.

**Comment by adzenith** [comment]
You can fork the repo, edit the Readme on Github, and send a pull request if you like!
