### ISSUE TITLE
Enabled origami_auto_zoom_on_focus - Not Zooming

### ISSUE THREAD

**Issue by GregLancaster71** [SublimeText/Origami#81]
Maybe I misunderstand how this should be functioning.  Is there a way make hovering change the column sizes?  Id like whichever column I am currently hovering over to stretch to the size specified.

**Comment by adzenith** [comment]
Focus implies that the pane is active, i.e. that you've switched to it. Hovering won't work. Sublime Text gives plugins very little ability to handle anything having to do with the mouse. See https://www.sublimetext.com/forum/viewtopic.php?f=6&t=8381#p40381

**Comment by adzenith** [comment]
Did the above answer your question? Can this issue be closed?

**Comment by Neospiro** [comment]
You should specify to set up origami_auto_zoom_on_focus  in the default settings file and not in "origami"'s one
