### ISSUE TITLE
Toggle Auto zoom on focus

### ISSUE THREAD

**Issue by nickbalestra** [SublimeText/Origami#82]
Would be great to being able to toggle "origami_auto_zoom_on_focus"

As sometime i need the auto_zoom_on_focus active and sometime, i.e when comparing snippets side by side i need this to be toggles off. 

Thoughts?

**Comment by adzenith** [comment]
Check out https://www.sublimetext.com/docs/3/settings.html, specifically the "Changing Settings with a Key Binding" section.

**Comment by nickbalestra** [comment]
Ah thanks, didn't know

**Comment by mkormendy** [comment]
For anyone having issues with the toggle_settings key-binding not working, I wrote some steps on how to get a toggle ability with this feature here: https://github.com/SublimeText/Origami/issues/95#issuecomment-226970281
