### ISSUE TITLE
Show filename in pane header / pane separation

### ISSUE THREAD

**Issue by mrsean2k** [SublimeText/Origami#91]
Is there any way that the filename / path of the file currently being edited in a pane can be displayed in a title bar for that pane?

There's an approximation to this with "View" -> "Show tabs", but that can quickly get messy when there are multiple files linked to a pane, and tabs take up a bit more mental space than a simple label.

I've looked at other plugins that automatically limit the number of tabs open on a MRU basis, but again this isn't quite what I'm after; I may have 40 files, split across 4 panes with 10 in each, but only want an indicator of the filename the pane is currently focused on.

One a semi-related note, is there any way to change the border style between panes, just bumping it up a pixel or two? Occasionally if two adjacent files are 'busy' it's difficult to see where one pane ends and the other begins.

**Comment by FichteFoll** [comment]
If you are on OSX, you need to set `"show_full_path": true` in your user settings (the general preferences). That will cause the filename of the currently edited file to be displayed in the window title.

**Comment by mrsean2k** [comment]
Thanks for the suggestion: I already have `show_full_path` set, but that only shows the filename / path of the file in the tab you're currently focused on. I'm really more interested in being able to easily see which pane is editing which file where I have multiple panes.

I thought I had a livable solution with a combination of the `goto_tab`, `move_tab` and `chain` plugins.

If I define two shortcuts like this:

```json
{ "keys": ["super+pagedown"], "command": "chain", "args":
	{"commands":
		[
			["goto_tab", {"tab": "1"}],
			["move_tab", {"position": "999"}],
			["goto_tab", {"tab": "1"}]
		]
	}
},

{ "keys": ["super+pageup"], "command": "chain", "args":
	{"commands":
		[
			["goto_tab", {"tab": "last"}],
			["move_tab", {"position": "0"}]
		]
	}
},
```

then `super+pagedown` and `super+pageup` will effectively rotate forwards / backwards through the tabs, always keeping the tab (and so filename) I'm editing in the same position at the left hand side of the pane.

The other tabs still show, but I could do something about that by styling the active / inactive tabs so there's more contrast between them.

*However* although this works fine for one pane, when I open a second pane, it appears to conflate the tabs on both panes when working out where to go next.

**Comment by adzenith** [comment]
Did you try the plugin mentioned in that Superuser post? Do you have a setup that works for you now?

**Comment by mrsean2k** [comment]
I abandoned using it in the end; with the tenkeyless keyboard and setup I use, I couldn't settle on range  of shortcuts and modifiers that meant I wasn't tripping over myself and accidentally creating, splitting, or destroying a pane. In it's place,I've just got faster at flicking between full windows for comparison etc. My limitation, not Origami's
