### ISSUE TITLE
Sublime crash on closing the first panel

### ISSUE THREAD

**Issue by Neospiro** [SublimeText/Origami#92]
Reproduce the behavior : 
- CTRL - SHIFT - N (open a new window for the test)
- CTRL - K , CTRL - RIGHT (create a panel at right)
- CTRL - K , CTRL - DOWN (create a panel at bottom)
- CTRL - K , DOWN (go to the bottom panel)
- CTRL - K , MAJ + UP (delete the top-left panel)

( On Sublime 3083 - Windows 7 64b )
<3

**Comment by adzenith** [comment]
Cannot repro. It works fine for me (I'm on Mac OS though).

**Comment by eparisio** [comment]
confirm on windows SO it crash closing the last tab in a panel with "origami_auto_close_empty_panes" at true

**Comment by JeppeMadsenDK** [comment]
I just experienced this issue on SublimeText 3 on Windows 7.

Like eparisio says, 'origami_auto_close_empty_panes' must be set to true.

Setting this to false, 'solved' the issue for me.

**Comment by adzenith** [comment]
This appears to be a bug in Sublime Text. I don't think I can solve it.

**Comment by titoBouzout** [comment]
You can prevent it by opening a new empty tab if theres no tabs in the window.

**Comment by adzenith** [comment]
This is related to Sublime Text's `close_windows_when_empty` preference (thanks @titoBouzout). If you set this to false you should not see this problem anymore.
