### ISSUE TITLE
Issue with turning on auto zoom

### ISSUE THREAD

**Issue by kdamken** [SublimeText/Origami#93]
Using Sublime Text 3, I put the following code under Sublime Text > Preferences > Package Settings > Origami > Settings - User:

{
	"origami_auto_zoom_on_focus": true	
}

I add that, save the file and restart Sublime and the auto zooming doesn't seem to work (while the manual command does). Is there some else I need to do?

Thanks!

**Comment by adzenith** [comment]
Confusingly, you have to put it in your normal preferences, not in the Origami preferences.

**Comment by kdamken** [comment]
Hey again,

Thanks for the follow up - I'm unsure what you mean but not in the origami preferences though. I thought I had put them in the correct spot. Any chance you can direct me to the right place?

**Comment by Namek** [comment]
@kdamken `Preferences` -> `Settings - User`

**Comment by kdamken** [comment]
@Namek Perfect! It works now, thank you for your help.

**Comment by adzenith** [comment]
Thanks @Namek!

**Comment by AXXOrganic** [comment]
IMO - You should put in to your documentation **how** to set your own preferences.
Setting this one: "origami_auto_zoom_on_focus": true
is easy....
But **how**does one set this option with a fraction of 0.5 ??????

**Comment by adzenith** [comment]
It is in the documentation:
> You can have Origami automatically zoom the active pane by setting `origami_auto_zoom_on_focus` in your user preferences. Set it to `true` for the default zoom, or set it to a user-definable fraction of the screen, such as `0.75`.

This is the relevant sentence:
> Set it to `true` for the default zoom, or set it to a user-definable fraction of the screen, such as `0.75`.

You can either set it to `true`, or to a fraction. I'm not really sure how to make it clearer. Feel free to send a PR if you have a suggestion!

**Comment by AXXOrganic** [comment]
Yes it is….

But more than 50% of your potential user have zero idea of how to even write an entry.
You presume knowledge of that. And thus limit your user base to only those know how to write entries in to Sublime Text…
Your feature is SOOO grand and fantastic and it is a shame that only folks with experience in programming dictionaries can use your strongest feature ;-)

— Best
Morten
