### ISSUE TITLE
Temporarily Disable Auto Zoom

### ISSUE THREAD

**Issue by hyphenistic** [SublimeText/Origami#95]
I use the auto zoom function along with Sublimerge.  When I fire up Sublimerge the panes get auto zoomed which I actually don't want.  Sublimerge has a setting to pause plugins when it is running and I have added Origami to that list but I'm guessing since the auto zoom feature is enabled in the Sublime Text preferences it is not getting disabled.  Is there a way to prevent Origami from auto zooming when Sublimerge is running?

**Comment by eparisio** [comment]
quote for implementing this!

**Comment by adzenith** [comment]
If Origami is disabled, it won't autozoom. I assume it's not actually getting disabled.
You can bind a key to toggle a preference as described here:
https://www.sublimetext.com/forum/viewtopic.php?f=3&t=6347#p41408
and then you can just hit that shortcut to turn auto zoom on and off.

**Comment by adzenith** [comment]
Okay to close this?

**Comment by hyphenistic** [comment]
Sure

**Comment by mkormendy** [comment]
I couldn't manage to get this to work the way it was suggested. I used the following setting in my Preference's User Keybindings:

`"keys": ["super+alt+\`"], "command": "toggle_setting", "args": { "setting": "origami_auto_zoom_on_focus", "value": 0.75 },`
