### ISSUE TITLE
Travel to pane creates pane if there is nowhere to travel

### ISSUE THREAD

**Issue by rpbaptist** [SublimeText/Origami#96]
```
| ----------|
|  1  |  2  |
| ----------|
```
In above example if I am in 1 and travel to the right I end up in 2 and vice versa. This is great.

When I am in 1 and travel to the left I create a new split pane. The same goes for two and moving to the right. Or in either one moving up and down for that matter.

In a simple view like this, it's not a problem. It doesn't happen often that I would make that mistake, but when it comes to travelling through multiple panes, and considering some unexpected movement where a pane isn't considered to be neighbouring, this becomes troublesome. I often create panes when I do not intend to do so.

I am completely sure I have no key bindings doing this for me as I am using ctrl+alt+arrow keys to move around. Creating panes is all done with a modifier before hand. (ctrl+space in my keys. Default are all ctrl+k.)

I am using Linux if that matters.

**Comment by ftoulemon** [comment]
You can change this behavior with this option:

    {
        "create_new_pane_if_necessary": false
    }

**Comment by rpbaptist** [comment]
Thanks very much. I wasn't aware of this option.

**Comment by dylanfisher** [comment]
:+1: thanks, didn't realize this option was added either!

**Comment by adzenith** [comment]
Should this option maybe be false by default? It sounds like a lot of people don't like this behaviour.

**Comment by dylanfisher** [comment]
I would vote for false by default. When new features are added that change existing behavior, it seems safer to default to false and then document the ability to enable the feature. 

Either way as long as its configurable it's not a big deal. 

It may be a good idea to document all the settings on main repo page. This could be the same settings that appear in Origami's default preferences. It also seems like the preferences documented in Automation https://github.com/SublimeText/Origami#automation could be included in the default preferences listed below.

```
{
    /**
     * The "saved_layouts" key holds a list of previously
     * saved layout settings. These can be set using the
     * "Origami: Save Current Layout" command, they can be
     * restored using the "Origami: Restore Saved Layout"
     * command and can be removed using the "Origami: Remove
     * Saved Layout" command.
     *
     * Valid format: {"nickname": XXXX, "cells": XXXX,
     *                "cols": XXXX, "rows": XXXX}
     */
    "saved_layouts": [],

    // Create a new pane when switching in a direction without one
    "create_new_pane_if_necessary": true
}
```

**Comment by axel22** [comment]
+1
