### ISSUE TITLE
Error when trying to restore layout

### ISSUE THREAD

**Issue by Bit-notes** [SublimeText/Origami#97]
I can create new windows from saved layout, but I get this error when trying to restore in current window:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "origami in /Users/Andrew/Library/Application Support/Sublime Text 3/Installed Packages/Origami.sublime-package", line 657, in run
NameError: global name 'settings' is not defined

**Comment by ArthurMaroulier** [comment]
Same error here after a fresh install on a mac.

**Comment by james-hart** [comment]
I noticed this same error, and just went through the code base. The code shows "if settings..." it should read "if self.settings()...". It doesn't look like this project is being actively maintained anymore though :(

**Comment by james-hart** [comment]
I submitted a pull request, but for now if you need no other changes, I have a forked master with just this fix: https://github.com/james-hart/Origami
Hopefully the project maintainer will merge it in

**Comment by adzenith** [comment]
Should be fixed. Thanks for the PR!
