### ISSUE TITLE
Add a zoom toggle?

### ISSUE THREAD

**Issue by perrupa** [SublimeText/Origami#99]
It would be great if there was a zoom toggle key. 

I find myself needing to zoom/unzoom frequently and it would be nice if the plugin were able to determine if the pane were zoomed already (`~= 90%` zoomed) and un-zoom, or set the zoom pane to 90% otherwise.

**Comment by adzenith** [comment]
Sounds like a (great idea)[https://github.com/SublimeText/Origami/issues/57]! :)

This isn't bound to a key by default, which is probably why nobody can find it. If I could go back in time there would only be one keybinding which would toggle zoom, but at this point if I changed it I think people would get confused. Any ideas?

**Comment by perrupa** [comment]
Woop! Sorry for the dupe, great minds think alike and all that :smile: 

If I could make a suggestion: I'd leave the unzoom keybinding as is but use `toggle_zoom_pane` as the default zoom-in. thoughts?

**Comment by adzenith** [comment]
Sadly, every time I change something that I think is minor and nobody will care about, I get a bunch of people opening issues about how it changed and they want it to go back.
https://xkcd.com/1172/

**Comment by adzenith** [comment]
I may be able to be convinced, though. I'll have to think about it.
